# Generated by Django 2.0.2 on 2018-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Display_Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
