# Generated by Django 2.0.2 on 2018-03-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_channel_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('channel_url', models.CharField(default='none', max_length=500)),
                ('channel_image_url', models.CharField(default='none', max_length=500)),
                ('analysis_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_channel_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.CharField(max_length=15)),
                ('view_count', models.BigIntegerField()),
                ('subscriber_count', models.BigIntegerField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_channel_main')),
            ],
        ),
        migrations.CreateModel(
            name='video_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('youtube_url', models.CharField(max_length=500)),
                ('publish_date', models.CharField(max_length=15)),
                ('analysis_status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='video_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('view', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('dislikes', models.BigIntegerField(max_length=15)),
                ('video_main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.video_main')),
            ],
        ),
    ]
