# Generated by Django 2.0.2 on 2018-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_channel_main_user_channel_sub_video_main_video_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_sub',
            name='dislikes',
            field=models.BigIntegerField(default=0),
        ),
    ]
