# Generated by Django 2.0.2 on 2018-04-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_channel_main_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_main',
            old_name='channel_name',
            new_name='video_name',
        ),
    ]
