# Generated by Django 2.0.2 on 2018-04-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180401_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_channel_sub',
            name='date1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='video_main',
            name='publish_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='video_sub',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
