# Generated by Django 2.0.2 on 2018-03-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_url', models.CharField(default='none', max_length=1000)),
                ('social_blade_url', models.CharField(default='none', max_length=1000)),
                ('channel_image_url', models.CharField(default='none', max_length=1000)),
                ('channel_pic_url', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='channel_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('view_count', models.BigIntegerField()),
                ('subscriber_count', models.BigIntegerField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel_main')),
            ],
        ),
    ]
