# Generated by Django 2.0.2 on 2018-03-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_main',
            name='channel_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
