# Generated by Django 2.0.2 on 2018-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20180323_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_main',
            name='channel_pic_url',
        ),
        migrations.AddField(
            model_name='channel_main',
            name='category',
            field=models.CharField(default='delete', max_length=100),
            preserve_default=False,
        ),
    ]
