# Generated by Django 2.0.2 on 2018-04-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20180327_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField()),
                ('date', models.TextField()),
                ('link', models.TextField()),
                ('comment_count', models.BigIntegerField()),
                ('view_count', models.BigIntegerField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel_main')),
            ],
        ),
    ]
