# Generated by Django 2.0.2 on 2018-04-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_video_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_data',
            old_name='date',
            new_name='upload_date',
        ),
    ]
