# Generated by Django 2.0.2 on 2018-04-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20180401_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_data',
            old_name='video_title',
            new_name='video_name',
        ),
    ]
