# Generated by Django 2.0.2 on 2018-04-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20180401_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_data',
            old_name='link',
            new_name='video_url',
        ),
    ]
