# Generated by Django 2.0.2 on 2018-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_auto_20180401_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_data',
            name='comment_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='view_count',
            field=models.FloatField(),
        ),
    ]
