# Generated by Django 2.0.2 on 2018-04-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us_form',
            name='phone',
        ),
    ]
